[project]
name = "sailserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "litestar>=2.15.2",
    "numpy>=2.2.5",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.2",
]
